# render.yaml
services:
  - type: web
    name: generative-ai-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: DATABASE_URL
        value: your_database_url_here
      - key: HF_API_KEY
        value: your_huggingface_api_key
